### ISSUE TITLE
[PE-D][Tester E] Accepted add command which should not be accepted according to UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-2/tp#231]
Type the following command (no decimal point in the stated dish price): \
add name/chicken rice price/2 ingredient/rice qty/200g

Expected error response, as according to UG:
![Screenshot 2023-11-03 at 17.06.28.png](https://raw.githubusercontent.com/itayrefaely/ped/main/files/5d76cf95-b060-485e-94ef-dbed6399d978.png)

Actual:
![Screenshot 2023-11-03 at 17.07.12.png](https://raw.githubusercontent.com/itayrefaely/ped/main/files/6acbe59b-3540-4d12-8246-25b98fe6c7e3.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: itayrefaely/ped#2

**Comment by ziyi105** [comment]
#251  similar bug @DextheChik3n
