### ISSUE TITLE
[PE-D][Tester D] Menu not stored to the data as they are entered by the user.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-2/tp#240]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
When the program us force exited using Cltr+C, the menu in the current context of the chatbot is not cached in the data folder. This can cause important entry by the user to not be reflected the next time the chatbot starts. To prevent his from happening, the menu/ingredient entries can be written to the text file as and when they are entered in by the user so that they can be retrieved the next time the user launches the chat bot in the case of a forceful or unforeseen exit.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: farissirraj/ped#9

**Comment by DextheChik3n** [comment]
add in user guide, only saves data when bye command is used, we won't save data if force exit is used
