### ISSUE TITLE
Standardise error message for decoding text file

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#323]
I noticed that all our messages have different numbers of line and format, should we standardise the error messages to make it look neater?
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/aad625e5-5c97-40c8-89c3-c87ef60d56b6)
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/b5db7a8a-28c9-4014-b8bd-681a69a64a63)

I was thinking we could follow the error message for menu.txt, which only has only one line and it's pretty concise, what do yall think?

**Comment by NaychiMin** [comment]
Yep, I was thinking the same too! I have implemented it in PR #321 and was merged into the main branch last night :)

**Comment by ziyi105** [comment]
I see, I will modify my error message accordingly, thanks!
