### ISSUE TITLE
Error thrown when loading empty menu file

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#328]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/7ef4df6e-7538-4d02-88bc-ed466a7aa178)
To recreate this error:  run the app with existing but empty orders and menu text file, one line: chicken | 800 | g  in pantrystock

**Comment by Cazh1** [comment]
Hi, can you please include the starting states of the save text files?

**Comment by ziyi105** [comment]
orders and menu files are completely empty

**Comment by ziyi105** [comment]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/8f7d4917-b7e0-4bb9-a868-54859635c688)

**Comment by Cazh1** [comment]
Thank you. I believe I found the error and rectified in my PR.
