### ISSUE TITLE
Text file syntax reminder output format

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#346]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/ac745e3f-8eb8-4ea3-8e73-a348f6826a43)

This is the messages shown when I start the application with invalid data in all three data files.  I noticed that there is no new line to separate the error msg and the syntax for the next text file (for example: `menu.txt: Invalid format...` is immediately followed by `Format for Orders.txt:`. 

May I know is this behaviour intended? Would the message be clearer if there was a line to separate messages for different text files?

**Comment by ziyi105** [comment]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/349920ce-fecf-45ce-bd5b-a5bf18a55292)

My conversation with @Cazh1 
I will help @NaychiMin  and @ShaniceTang  add a new line after the error msg for decoder

**Comment by ShaniceTang** [comment]
Could we use printLine() rather than a new line? It might a clearer divider. 

Thank you @ziyi105 for helping us add! :D

**Comment by ziyi105** [comment]
ohh that's a good idea, thanks Shanice!
