### ISSUE TITLE
Unused UiTest class

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#349]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/67761a3e-c5aa-4bdb-afdd-f07808ea1b73)
I noticed that this class is empty and it's not used, is there any reason why it is needed?

**Comment by ShaniceTang** [comment]
Ah oops my bad, I must have forgotten about it. The class is not needed I will delete it.

**Comment by ziyi105** [comment]
Thanks for the clarification!
