### ISSUE TITLE
Buy ingredient: not displaying error message for the valid range of price values

### ISSUE THREAD

**Issue by DextheChik3n** [AY2324S1-CS2113-T17-2/tp#371]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/35828587/32494a08-41a9-49a4-86ff-db692f5bc876)

By right it should print an error message to tell the user the qty should be between a range

Perhaps the buy_ingredient parser regex needs to be changed to accept the values after the "ingredient/" and "qty/" tags
then add pass the qty value through a function that checks if it is within a range

**Comment by ShaniceTang** [comment]
Hellos I've changed my buy ingredient regex to accept negative quantity. Maybe there is some mix up with the error handling in parseIngredients?
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/110757597/7842b983-4d45-49df-88b3-fa790f0e386f)

**Comment by DextheChik3n** [comment]
Oh ok i see what's wrong... I think its something to do with my parseIngredient function in the Parser class
