### ISSUE TITLE
Wrong ingredient name case for view_stock

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#372]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/355b8b8a-4bd1-4953-a701-9412331fe197)

I buy RICE first and followed by rice, but in view_stock the ingredient name is still RICE, should we convert everything to lowercase in view_stock?

**Comment by DextheChik3n** [comment]
So when we display the dish name or ingredient name we just display it as all lowercase?
