### ISSUE TITLE
add_order: available dishes phrasing

### ISSUE THREAD

**Issue by ziyi105** [AY2324S1-CS2113-T17-2/tp#376]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82555990/ce85a49c-945d-412c-b8df-4f6d859de2c5)

Perhaps rephrasing it to "Number of dishes available/left" would be clearer?

**Comment by NaychiMin** [comment]
Thank you for bringing this up! However, I feel that the current message might be more informative for the user as it entails what is listed below and the significance of listing it ("for the next order"). Would changing dishes to "each dish" make it slightly clearer?
"Listed below are the availability of each dish for the next order!"

**Comment by ziyi105** [comment]
Ohh I meant the "Available Dishes: 8", maybe changing it to "Number of Available Dishes Left: 8" would be more I formative?

**Comment by NaychiMin** [comment]
Okay! Thank you for the clarification!
