### ISSUE TITLE
Pantry Stock decoder: unintended message printed

### ISSUE THREAD

**Issue by DextheChik3n** [AY2324S1-CS2113-T17-2/tp#379]
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/35828587/e4570a1d-00a0-40a4-bdd9-9c20ead6d165)

changing the hash string to a really big number caused an unintended message to be printed out

**Comment by ziyi105** [comment]
The hash string is being decoded as a normal data text now. Do you think this can be counted as a bug? Or we can argue that since they edited the text file using the wrong format the app cannot differentiate which one is hash string which one is data alr

**Comment by Cazh1** [comment]
Yes once they edit the string is it hard to differentiate between a very long data or very long hash string. It would be risky to assume one over the other.
Regardless there is a string added to notify users that we found changes to what was supposed to be the hash string
![image](https://github.com/AY2324S1-CS2113-T17-2/tp/assets/82131563/7f2221c6-2494-4098-8844-cf810380626f)

**Comment by ziyi105** [comment]
Thanks for your input, i guess can't do anything about it now since we dont have much time left. I will just add this under UG known issues
